export enum DomainExceptionCode {
  ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
  ENTITY_ALREADY_EXISTS = "ENTITY_ALREADY_EXISTS",
  DATABASE_ERROR = "DATABASE_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
}
